---
title: "Abstract Submission Notes"
author: "by Tim Bender"
subtitle: "useR Conference 2025: Durham, NC"
output: 
  html_document:
    code_download: TRUE
    code_folding: "show"
    toc: TRUE
    toc_float: TRUE
    toc_depth: "2"
params: 
date: "Updated: 2/19/25"
---

## Important Dates

## Submission Format

- The title of the tutorial
- Abstract
- A brief outline
- The broad topic it covers
- The learning goals
- Time zone preference and time slot (please mention at least three different time zones you are comfortable with) - this is only necessary for the online component of the conference.
- Length of the tutorial (in minutes or hours)
- Language in which the tutorial can be taught.
- The intended audience (beginners, advances, etc.)
- Pedagogical method of teaching
- The maximum number of attendees
- Motivation to teach this tutorial at useR!
  - Links to the Tutorial materials and/or web page (If there exists).
- Prerequisites / requirements
- Material sharing (license), recording consent
- A brief biography of the instructors



## Sources / Reference

- [LINK: All about the Abstract Submission](https://rconf.gitlab.io/userknowledgebase/main/tutorials-how-to.html)
- [LINK: useR 2025 main webpage](https://user2025.r-project.org/)
