---
title: ""
author: "Tim Bender"
date: "Submitted: `r Sys.Date()`"
output:
  html_document:
    code_download: TRUE
    code_folding: "hide"
    toc: TRUE
    toc_float: TRUE
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abstract

One hobbyist's attempt to use R to never miss a solar or lunar eclipse again.

## Outline

## Broad Topic Covered

## Learning Goals

1.  

2.  You don't have to know ~~everything~~ ~~anything~~ as much as you think you do.

3.  Evolving your skills and knowledge throughout a project lifecycle: pros and cons.

## Timezone Preference(s)

## Duration

## Language

## Intended Audience

- Solar and lunar eclipse seekers
- Beginners and hobbyists looking for:
  -   project idea inspiration,
  -   a better understanding on how to approach the project lifecycle, and
  -   how to deal with the "too many ideas but not enough progress" monster.

## Pedagogical Method of Teaching

## Maximum Number of Attendees

## Motivation to Teach this Tutorial at useR!

## Supplemental Material Links

#### Tutorial materials

-   Future Solar and Lunar Eclipses Visible from Your Current Location ([Shiny webapp](https://tim-bender.shinyapps.io/shiny_all_eclipses/))

#### Web Page (if applicable)

## Prerequisites / requirements

## License, Material sharing, recording consent

## Biography

#### Tim Bender, (title)

-   [hold for bio]
-   [LinkedIn](https://www.linkedin.com/in/tim-bender-238870171/)
-   [github](https://github.com/benda18)
