---
title: "ggplot2 Brushing"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
    # fig_height: 4
    # fig_width: 4
    #social: menu
    source_code: embed
   
runtime: shiny
---

```{r global, include=FALSE}
# # load data in 'global' chunk so it can be shared by all users of the dashboard
# library(datasets)
# mtcars2 <- mtcars[, c("mpg", "cyl", "wt")]
library(leaflet)
```


```{r}


# # Reactive that returns the whole dataset if there is no brush
# selectedData <- reactive({
#   data <- brushedPoints(mtcars2, input$plot1_brush)
#   if (nrow(data) == 0) # if you use brush and select nothing.
#     data <- mtcars2
#   data
# })
```

<!-- Column {data-width=650} -->
Column
-----------------------------------------------------------------------

<!-- ### Miles Per Gallon vs. Weight {data-width=600} -->
### Miles Per Gallon vs. Weight

```{r}
leaflet() %>%
  addTiles()
# library(ggplot2)
# plotOutput("plot1", brush = brushOpts(id = "plot1_brush"))
# output$plot1 <- renderPlot({
#   ggplot(mtcars2, aes(wt, mpg)) + geom_point()
# })

```

<!-- ### Miles Per Gallon and Cylinders {data-width=400} -->
### Miles Per Gallon and Cylinders
```{r}
# renderPlot({
#   ggplot(selectedData(), aes(factor(cyl), mpg))  + geom_boxplot()
# })
print("foo1")
```

Column {data-width=350}
-----------------------------------------------------------------------

<!-- ### Car Details {data-width=400} -->
### Car Details
```{r}
# renderTable({
#   selectedData()
# })
"foo2"
```
